import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Button } from 'react-bootstrap'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope } from '@fortawesome/free-solid-svg-icons'
import TodoList from './TodoList';


export default function Home() {
  return (
    <>
      <Head>
        <title>Todos App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Todo List</h1>
        <TodoList />
      </main>
    </>
  )
}
